table financials
	lineageTag: 7a9a5616-4052-4cf0-97e6-103812fdd10e

	/// Total number of units sold across all products, segments, and countries.
	measure 'Total Units Sold' = SUM('financials'[Units Sold])
		formatString: #,##0
		displayFolder: Measures\Quantity
		lineageTag: 89e3116b-8561-4f93-b13d-fd56c000ed62

	/// Total gross sales revenue before discounts are applied. Equal to Units Sold × Sale Price.
	measure 'Total Gross Sales' = SUM('financials'[Gross Sales])
		formatString: #,##0.00
		displayFolder: Measures\Value
		lineageTag: e453ae51-3713-4590-bd10-d2f9d9acdd1d

	/// Total discount amount deducted from gross sales.
	measure 'Total Discounts' = SUM('financials'[Discounts])
		formatString: #,##0.00
		displayFolder: Measures\Value
		lineageTag: 5fc73522-abca-4134-b3f6-de684ac81a2e

	/// Total net sales revenue after discounts (Gross Sales minus Discounts). Use this as the primary revenue measure.
	measure 'Total Sales' = SUM('financials'[Sales])
		formatString: #,##0.00
		displayFolder: Measures\Value
		lineageTag: c4096048-d4ac-4cc6-938f-e856d9ca26c3

	/// Total Cost of Goods Sold (COGS). Represents the direct costs attributable to the production of the goods sold.
	measure 'Total COGS' = SUM('financials'[COGS])
		formatString: #,##0.00
		displayFolder: Measures\Value
		lineageTag: 37dfec7e-e87d-4285-be51-f29430070566

	/// Total profit calculated as Net Sales minus COGS.
	measure 'Total Profit' = SUM('financials'[Profit])
		formatString: #,##0.00
		displayFolder: Measures\Value
		lineageTag: ab360f59-c473-428c-889b-6b8357c6a353

	/// Gross profit margin as a percentage of net sales (Total Profit ÷ Total Sales). Indicates profitability relative to revenue.
	measure 'Gross Margin (%)' = DIVIDE([Total Profit], [Total Sales], BLANK())
		formatString: 0.00%
		displayFolder: Measures\Value
		lineageTag: 0d6d328c-0264-46da-81e4-a6f03eea589b

	/// Discount rate as a percentage of gross sales (Total Discounts ÷ Total Gross Sales). Indicates the proportion of gross revenue given away as discounts.
	measure 'Discount Rate (%)' = DIVIDE([Total Discounts], [Total Gross Sales], BLANK())
		formatString: 0.00%
		displayFolder: Measures\Value
		lineageTag: 1e14d535-bc06-43b6-9a74-e956aad548d9

	column Segment
		dataType: string
		lineageTag: fc9b883d-bcdb-426b-89ef-1fba68a1df82
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 61f8b48f-dcd7-46ca-ace2-97e70d550cec
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column Product
		dataType: string
		lineageTag: feac4cce-d70f-428b-a24d-90864f74eae9
		summarizeBy: none
		sourceColumn: Product

		annotation SummarizationSetBy = Automatic

	column 'Discount Band'
		dataType: string
		lineageTag: f5029d1b-0a93-4a2d-8c8e-4a3eb9eab6f9
		summarizeBy: none
		sourceColumn: Discount Band

		annotation SummarizationSetBy = Automatic

	column 'Units Sold'
		dataType: double
		isHidden
		lineageTag: e015f6ab-f99c-4912-8cdc-877f17181fdc
		summarizeBy: none
		sourceColumn: Units Sold

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Manufacturing Price'
		dataType: int64
		formatString: 0
		lineageTag: e0206607-4b75-4d67-b7f5-81f0150a8d8a
		summarizeBy: none
		sourceColumn: Manufacturing Price

		annotation SummarizationSetBy = Automatic

	column 'Sale Price'
		dataType: int64
		formatString: 0
		lineageTag: 905cc2b9-59b0-4bd9-b7b7-e4625fd549c1
		summarizeBy: none
		sourceColumn: Sale Price

		annotation SummarizationSetBy = Automatic

	column 'Gross Sales'
		dataType: double
		isHidden
		lineageTag: 0847b448-6d13-48d0-ba6f-981f2ca7c38e
		summarizeBy: none
		sourceColumn: Gross Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Discounts
		dataType: double
		isHidden
		lineageTag: 6a1d9495-e50a-4098-8c42-9fa6c3956664
		summarizeBy: none
		sourceColumn: Discounts

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Sales
		dataType: double
		isHidden
		lineageTag: 6e856828-bef8-4a50-be16-f72fce0d4679
		summarizeBy: none
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column COGS
		dataType: double
		isHidden
		lineageTag: 0314b2f4-c54d-4cf2-a049-bcf19a9e1bc2
		summarizeBy: none
		sourceColumn: COGS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Profit
		dataType: double
		isHidden
		lineageTag: 677556b4-f018-45a2-bf97-a04a63bdc42b
		summarizeBy: none
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: ddcaa492-99a3-4006-acf2-9bc28c6238f0
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Month Number'
		dataType: int64
		formatString: 0
		lineageTag: 203cb5e7-93eb-4d40-8ed2-370adbafce8a
		summarizeBy: none
		sourceColumn: Month Number

		annotation SummarizationSetBy = Automatic

	column 'Month Name'
		dataType: string
		lineageTag: cb49eed2-1c8a-460b-8316-f02eb14d8500
		summarizeBy: none
		sourceColumn: Month Name

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 0b67dbda-75ce-43e0-be92-2dcb970bfc78
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	partition financials = m
		mode: import
		source =
				let
				 Source = Excel.Workbook(File.Contents("C:\Program Files\WindowsApps\Microsoft.MicrosoftPowerBIDesktop_2.138.828.0_x64__8wekyb3d8bbwe\bin\SampleData\Financial Sample.xlsx"), null, true),
				    financials_Table = Source{[Item="financials",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(financials_Table,{{"Segment", type text}, {"Country", type text}, {"Product", type text}, {"Discount Band", type text}, {"Units Sold", type number}, {"Manufacturing Price", Int64.Type}, {"Sale Price", Int64.Type}, {"Gross Sales", type number}, {"Discounts", type number}, {" Sales", type number}, {"COGS", type number}, {"Profit", type number}, {"Date", type date}, {"Month Number", Int64.Type}, {"Month Name", type text}, {"Year", Int64.Type}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{" Sales", "Sales"}})
				in
				 #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

